using UnityEngine;

public class TesteGiro : MonoBehaviour
{
    private Gyroscope giro;

    void Start()
    {
        if (SystemInfo.supportsGyroscope)
        {
            giro = Input.gyro;
            giro.enabled = true;
            Debug.Log("Girosc처pio ativado!");
        }
        else
        {
            Debug.Log("Este dispositivo n찾o suporta girosc처pio.");
        }
    }

    void Update()
    {
        // Rotaciona o objeto conforme o girosc처pio (modo bruto pra teste)
        transform.rotation = new Quaternion(-giro.attitude.x, -giro.attitude.y, giro.attitude.z, giro.attitude.w);
    }
}
